-- TABLE 5 : Reviews 
ALTER TABLE reviews DROP CONSTRAINT PK_review; 
ALTER TABLE reviews DROP CONSTRAINT FK_Reviews_Rentals; 
ALTER TABLE reviews DROP CONSTRAINT CHK_text; 
ALTER TABLE reviews MODIFY (rev_date DEFAULT NULL); 
ALTER TABLE reviews DROP CONSTRAINT CHK_stars; 
DROP SEQUENCE review_id_seq; 
DROP TABLE reviews; 

-- TABLE 4 : Rentals  
ALTER TABLE rentals DROP CONSTRAINT PK_rental; 
ALTER TABLE Rentals DROP CONSTRAINT FK_Ren_apt_id; 
ALTER TABLE Rentals DROP CONSTRAINT FK_Ren_tnt_id; 
DROP TABLE rentals; 

-- TABLE 3 : Tenants 
ALTER TABLE tenants DROP CONSTRAINT PK_tenant_id; 
ALTER TABLE tenants DROP CONSTRAINT CHK_Tname; 
ALTER TABLE tenants DROP CONSTRAINT CHK_Tsurname; 
ALTER TABLE tenants DROP CONSTRAINT CHK_Tgender; 
ALTER TABLE tenants DROP CONSTRAINT CHK1_Temail; 
ALTER TABLE tenants DROP CONSTRAINT CHK2_Temail; 
ALTER TABLE tenants DROP CONSTRAINT CHK_Ttel; 
ALTER TABLE tenants DROP CONSTRAINT CHK_num_of_tenants; 
ALTER TABLE tenants MODIFY (num_of_tenants DEFAULT NULL); 
ALTER TABLE tenants DROP CONSTRAINT CHK_country; 
DROP SEQUENCE tnt_id_seq; 
DROP TABLE tenants; 

-- TABLE 2 : APARTMENTS 
ALTER TABLE Apartments DROP CONSTRAINT PK_apartment; 
ALTER TABLE Apartments DROP CONSTRAINT FK_tin; 
ALTER TABLE Apartments DROP CONSTRAINT CHK_area; 
ALTER TABLE Apartments DROP CONSTRAINT CHK_price; 
ALTER TABLE Apartments DROP CONSTRAINT CHK_streetName; 
ALTER TABLE Apartments DROP CONSTRAINT CHK_zip_code; 
ALTER TABLE Apartments DROP CONSTRAINT CHK_Acity; 
DROP SEQUENCE apartment_id_seq; 
DROP TABLE Apartments; 

-- Table 1: Owners 
ALTER TABLE Owners DROP CONSTRAINT PK_owner; 
ALTER TABLE Owners DROP CONSTRAINT CHK_tin; 
ALTER TABLE Owners DROP CONSTRAINT CHK_Oname; 
ALTER TABLE Owners DROP CONSTRAINT CHK_Osurname; 
ALTER TABLE Owners DROP CONSTRAINT CHK_Ogender; 
ALTER TABLE Owners DROP CONSTRAINT CHK1_Oemail; 
ALTER TABLE Owners DROP CONSTRAINT CHK2_Oemail; 
ALTER TABLE Owners DROP CONSTRAINT CHK_Ocity; 
ALTER TABLE Owners DROP CONSTRAINT CHK_Otel; 
DROP TABLE Owners; 

PURGE RECYCLEBIN 

SELECT * FROM TAB WHERE TNAME NOT LIKE 'BIN%';  -- DISPLAYS TABLES TO CONFIRM IF THE DATABASE IS DROPPED 