-- 1. Tenants whose surname starts with A and ends with S. 
SELECT tnt_id, name, surname  
FROM tenants  
WHERE surname LIKE 'A%S'; 

-- 2. Total number of tenants per country.
SELECT country, count(*)  
FROM tenants  
GROUP BY country; 

-- 3. Which apartment was the most popular (was rented the most times)?
SELECT apt_id, COUNT(*) AS rental_count  
FROM Rentals  
GROUP BY apt_id  
ORDER BY rental_count DESC; 

-- 4. The owners in an ascending order and the apartments they own.
SELECT o.surname AS Owner_Surname, o.name AS Owner_Name, o.TIN AS Owner_TIN, a.apt_id AS Apartment_ID, a.street_name AS Apartment_Street, a.street_num AS Apartment_Street_Number, a.city AS Apartment_City 
FROM Owners o 
LEFT JOIN Apartments a ON o.TIN = a.tin 
ORDER BY o.surname ASC, o.name ASC; 

-- 5. Which owner has the most apartments?
SELECT o.tin, o.surname, o.name, COUNT(a.apt_id) AS num_apartments    
FROM owners o    
JOIN apartments a ON o.tin = a.tin    
GROUP BY o.tin, o.name, o.surname    
ORDER BY num_apartments DESC    
FETCH FIRST 1 ROWS WITH TIES;

-- 6. Which city has the most expensive apartment?
SELECT city, MAX(price) AS Max_Price 
FROM Apartments 
GROUP BY city 
ORDER BY Max_Price DESC 
FETCH FIRST 1 ROWS ONLY;

-- 7. How many reviews were submitted in the year 2020?
SELECT COUNT(review_id) AS review_count  
FROM Reviews
WHERE TO_CHAR(rev_date, 'YYYY') = '2020';

-- 8. Which tenant has submitted the most reviews?
SELECT t.surname, t.name, COUNT(r.review_id) AS num_reviews    
FROM tenants t    
JOIN reviews r ON t.tnt_id = r.tnt_id    
GROUP BY t.surname, t.name    
ORDER BY num_reviews DESC    
FETCH FIRST 1 ROWS WITH TIES; 

-- 9. Which apartments were rented in August (regardless of year)?
SELECT DISTINCT a.apt_id, a.street_name, a.street_num, a.city, r.start_date  
FROM apartments a  
JOIN rentals r ON a.apt_id = r.apt_id  
WHERE TO_CHAR(r.start_date, 'MM') = '08'; 

-- 10. How many apartments have never been rented? 
SELECT COUNT(*) AS Unrented_Apartments  
FROM apartments a 
LEFT JOIN rentals r ON a.APT_ID = r.APT_ID  
WHERE r.APT_ID IS NULL; 

-- 11. The oldest female tenant.
SELECT NAME, SURNAME, DATE_OF_BIRTH 
FROM tenants t  
WHERE t.GENDER = 'F'    
ORDER BY DATE_OF_BIRTH ASC  
FETCH FIRST 1 ROWS ONLY; 

-- 12. The owners who have never rented their apartments.
SELECT o.TIN, o.name, o.surname  
FROM owners o  
WHERE o.TIN NOT IN ( 
	SELECT DISTINCT a.tin  
	FROM apartments a  
	JOIN rentals r ON a.apt_id = r.apt_id  
); 

-- 13. The tenants who have rented apartments on a street that contains the word "SAINT".
SELECT DISTINCT t.name AS Tenant_Name, t.surname AS Tenant_Surname, a.street_name AS Apartment_Street, a.city AS Apartment_City 
FROM Rentals r 
JOIN Tenants t ON r.tnt_id = t.tnt_id 
JOIN Apartments a ON r.apt_id = a.apt_id 
WHERE a.street_name LIKE '%SAINT%'; 

-- 14. The apartments in descending order, based on the average of their review scores.
SELECT a.apt_id, a.street_name,a.street_num,a.zip_code,a.city,a.floor, avg(r.stars) as Average_Stars 
FROM apartments a  
JOIN reviews r ON a.APT_ID = r.APT_ID  
GROUP BY a.apt_id, a.street_name,a.street_num,a.zip_code, a.city,a.floor  
ORDER BY Average_Stars DESC; 

-- 15. Which apartment in “THESSALONIKI” has the highest review average?
SELECT r.apt_id,AVG(r.stars) AS review_average
FROM Reviews r
JOIN Apartments a ON r.apt_id=a.apt_id
WHERE a.city = 'THESSALONIKI' 
GROUP BY r.apt_id
ORDER BY review_average DESC
FETCH FIRST 1 ROWS ONLY;

-- 16. Which tenant has the most rentals?
SELECT t.name, t.surname, COUNT(r.apt_id) AS num_rentals
FROM tenants t    
JOIN rentals r ON t.tnt_id = r.tnt_id    
GROUP BY t.name, t.surname    
ORDER BY num_rentals DESC    
FETCH FIRST 1 ROWS WITH TIES;

-- 17. The average review score for male and female tenants.
SELECT t.gender AS Tenant_Gender, AVG(r.stars) AS Average_Score 
FROM Reviews r 
JOIN Tenants t ON r.tnt_id = t.tnt_id 
WHERE t.gender IN ('F', 'M') 
GROUP BY t.gender; 

-- 18. Total rentals per city, categorized by gender, sorted by popularity.
SELECT t.gender, a.city, COUNT(*) AS rental_count  
FROM rentals r  
JOIN apartments a ON r.apt_id = a.apt_id  
JOIN tenants t ON r.tnt_id = t.tnt_id  
GROUP BY t.gender, a.city  
ORDER BY t.gender, rental_count DESC; 

-- 19. Create a username for each tenant by concatenating the first 4 letters of their name and the first 4 letters of their surname. 
SELECT tnt_id, name, surname, concat(substr(name, 1, 4), substr(surname, 1, 4)) as username 
FROM tenants; 

-- 20. The total revenue generated by rentals per year (revenue is calculated as price * number of days rented).
SELECT TO_CHAR(r.start_date, 'YYYY') AS rental_year, SUM(a.price * (r.end_date - r.start_date)) AS total_revenue  
FROM apartments a  
JOIN rentals r ON a.apt_id = r.apt_id  
GROUP BY TO_CHAR(r.start_date, 'YYYY')  
ORDER BY rental_year; 

-- a1. All the data from the rentals table.
SELECT * FROM rentals; 

-- a2. All the data from the owners table.
SELECT * FROM owners; 

-- b1. All apartments, ordered by ID in reverse order.
SELECT apt_id, city, area  
FROM apartments  
ORDER BY apt_id desc; 

-- b2. All tenants, ordered by ID in reverse order.
SELECT tnt_id, surname, date_of_birth  
FROM tenants  
ORDER BY tnt_id desc; 

-- c1. All tenants from the United States.
SELECT * FROM tenants  
WHERE country = 'UNITED STATES'; 

-- c2. All tenants whose name starts with A and ends with IS or whose name ends with IA. 
SELECT * FROM tenants  
WHERE name LIKE 'A%IS' 
	OR name LIKE '%IA'; 

-- c3. All tenants who are not from Greece or the United States and were born between 1980 and 2000. 
SELECT * FROM tenants  
WHERE country NOT IN ('GREECE','UNITED STATES')  
	AND TO_CHAR(date_of_birth, 'YYYY') BETWEEN '1980' AND '2000'; 

-- d1. The tenants who rented apartment 11.
SELECT DISTINCT t.name, t.surname
FROM tenants t  
JOIN rentals ren ON ren.tnt_id = t.tnt_id  
WHERE ren.apt_id = 11; 

-- d2. The tenants who rented apartments with a price less than 92 while the number of tenants in the apartment is less than or equal to 3. 
SELECT distinct t.name, t.surname, t.email  
FROM tenants t  
JOIN rentals ren ON ren.tnt_id=t.tnt_id	  
JOIN apartments apt ON apt.apt_id=ren.apt_id  
WHERE t.num_of_tenants <= 3  
	AND apt.price < 92; 

-- d3. Detailed information for all rentals that received 2 stars or lower.
SELECT o.name, o.surname, o.email AS owner_email, ren.apt_id, t.name, t.surname, t.email AS tenant_email, rev.start_date AS rental_date FROM owners o 
JOIN apartments apt ON apt.tin = o.tin  
JOIN rentals ren ON ren.apt_id = apt.apt_id  
JOIN tenants t ON t.tnt_id = ren.tnt_id  
JOIN reviews rev ON rev.tnt_id = ren.tnt_id AND rev.apt_id = ren.apt_id AND rev.start_date = ren.start_date  
WHERE rev.stars <= 2; 

-- e1. The average price of apartments per city, rounded to 2 decimal places.
SELECT city, ROUND(AVG(price),2) AS average_price 
FROM Apartments 
GROUP BY city; 

-- e2. The number of rentals for each tenant.
SELECT t.tnt_id, t.name, t.surname, COUNT(*) AS rental_count 
FROM Rentals r 
JOIN Tenants t ON r.tnt_id = t.tnt_id 
GROUP BY t.tnt_id, t.name, t.surname; 

-- e3. The number of apartments owned by each owner.
SELECT o.TIN AS owner_tin, o.name AS owner_name, o.surname AS owner_surname, COUNT(*) AS apartment_count 
FROM Apartments a 
JOIN Owners o ON a.tin = o.TIN 
GROUP BY o.TIN, o.name, o.surname; 