-- TABLE 5 : Reviews 
ALTER TABLE Reviews DROP CONSTRAINT PK_review; 
ALTER TABLE Reviews DROP CONSTRAINT FK_Reviews_Rentals; 
ALTER TABLE Reviews DROP CONSTRAINT CHK_text; 
ALTER TABLE Reviews MODIFY (rev_date DEFAULT NULL); 
ALTER TABLE Reviews DROP CONSTRAINT CHK_stars; 
DROP SEQUENCE review_id_seq; 
DROP TABLE Reviews; 

-- TABLE 4 : Rentals  
ALTER TABLE Rentals DROP CONSTRAINT PK_rental; 
ALTER TABLE Rentals DROP CONSTRAINT FK_Ren_apt_id; 
ALTER TABLE Rentals DROP CONSTRAINT FK_Ren_tnt_id; 
ALTER TABLE Rentals DROP CONSTRAINT CHK_Ren_dates;
DROP TABLE Rentals; 

-- TABLE 3 : Tenants 
ALTER TABLE Tenants DROP CONSTRAINT PK_tenant_id; 
ALTER TABLE Tenants DROP CONSTRAINT CHK_Tname; 
ALTER TABLE Tenants DROP CONSTRAINT CHK_Tsurname; 
ALTER TABLE Tenants DROP CONSTRAINT CHK_Tgender; 
ALTER TABLE Tenants DROP CONSTRAINT CHK_Temail; 
ALTER TABLE Tenants DROP CONSTRAINT CHK_Ttel; 
ALTER TABLE Tenants DROP CONSTRAINT CHK_num_of_tenants; 
ALTER TABLE Tenants MODIFY (num_of_tenants DEFAULT NULL); 
ALTER TABLE Tenants DROP CONSTRAINT CHK_country; 
DROP SEQUENCE tnt_id_seq; 
DROP TABLE Tenants; 

-- TABLE 2 : APARTMENTS 
ALTER TABLE Apartments DROP CONSTRAINT PK_apartment; 
ALTER TABLE Apartments DROP CONSTRAINT FK_tin; 
ALTER TABLE Apartments DROP CONSTRAINT CHK_area; 
ALTER TABLE Apartments DROP CONSTRAINT CHK_price; 
ALTER TABLE Apartments DROP CONSTRAINT CHK_streetName; 
ALTER TABLE Apartments DROP CONSTRAINT CHK_zip_code; 
ALTER TABLE Apartments DROP CONSTRAINT CHK_Acity; 
DROP SEQUENCE apartment_id_seq; 
DROP TABLE Apartments; 

-- Table 1: Owners 
ALTER TABLE Owners DROP CONSTRAINT PK_owner; 
ALTER TABLE Owners DROP CONSTRAINT CHK_tin; 
ALTER TABLE Owners DROP CONSTRAINT CHK_Oname; 
ALTER TABLE Owners DROP CONSTRAINT CHK_Osurname; 
ALTER TABLE Owners DROP CONSTRAINT CHK_Ogender; 
ALTER TABLE Owners DROP CONSTRAINT CHK_Oemail;
ALTER TABLE Owners DROP CONSTRAINT CHK_Ocity; 
ALTER TABLE Owners DROP CONSTRAINT CHK_Otel; 
DROP TABLE Owners; 

PURGE RECYCLEBIN;

-- t6. Display all table names in the current schema to confirm that all tables have been dropped
SELECT * FROM TAB WHERE TNAME NOT LIKE 'BIN%';  